name: ðŸš€ Deploy Nuxt.js 3 App to VPS
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: ðŸ—ï¸ Build
    runs-on: ubuntu-latest
    env:
      APP_DIR: /var/www/dibodev.fr
    steps:
      - name: ðŸ“¥ Checkout repository
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: ðŸ“¦ Install dependencies
        run: npm ci

      - name: ðŸ› ï¸ Build App
        run: npm run build

      - name: ðŸ—‘ï¸ Remove node_modules from .output/server
        run: rm -rf .output/server/node_modules

      - name: ðŸ“ Modify package.json
        run: |
          mv .output/server/package.json .output/package.json
          jq '{name: .name, version: .version, private: .private, dependencies: .bundledDependencies}' .output/package.json > .output/temp.json
          mv .output/temp.json .output/package.json

      - name: ðŸ“ Create server.js
        run: echo "import('./server/index.mjs');" > .output/server.js

      - name: ðŸ“¤ Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".output/"
          target: ${{ env.APP_DIR }}/html

      - name: ðŸš€ Install dependencies and restart Server with PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.APP_DIR }}/html/.output
            npm install
            pm2 restart dibodev.fr || pm2 start server.js --name dibodev.fr
